/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package InventoryManagement;

import javafx.application.Application;
import javafx.fxml.FXMLLoader;
import javafx.stage.Stage;
import javafx.scene.Parent;
import javafx.scene.Scene;

import java.sql.Connection;
import java.sql.Statement;

public class App extends Application {

   @Override
   public void start(Stage primaryStage) throws Exception {
      DBConnect co = new DBConnect();
      String query = "insert into product values(4, 'SVR45YR666HR', 'papera', 100, 3.5)";
      Statement stat = co.connectToDB().createStatement();
      stat.execute(query);

      Parent root = FXMLLoader.load(getClass().getResource("/main.fxml"));
      Scene scene = new Scene(root);
      primaryStage.setTitle("Inventory Management");
      primaryStage.setScene(scene);
      primaryStage.show();

   }

   public static void main(String[] args) {
      launch();
   }
}
